<?php
use Migrations\AbstractMigration;

class AddFunproducts extends AbstractMigration
{
    /**
     * Change Method.
     *
     * More information on this method is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-change-method
     * @return void
     */
    public function change()
    {
        $this->query("
            INSERT INTO `products` (`id`, `name`, `article`, `slug`, `description`, `price_ex`, `vat`, `high_shipping`, `active`, `created`, `modified`, `deleted`, `layout`, `product_group`) VALUES
            (UUID(), 'Beer', 'FBEER', 'beer', '<div>Deze wollige teddybeer is ideaal om mee te knuffelen, mee te gaan slapen of om cadeau te doen.<br/>De beer is bruin, 22cm hoog en heerlijk zacht. Het T-shirt wordt bedrukt met een foto in de maat 7,5cm breed x 5cm hoog (foto in de breedte) of 4cm breed x 5cm hoog (foto in de lengte).</div>', 19.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Mok blauw', 'FBEKER_BLAUW', 'mok-blauw', 'Geniet van je koffie of thee uit deze mok met de favoriete foto erop gedrukt. Dankzij de speciale druktechniek is de mok vaatwasmachinebestendig en kan deze in de magnetron. <br/>Deze mok is 9,5cm hoog en heeft een doorsnee van 8,2cm. Het handvat en de binnen kleur van deze mok zijn blauw.', 16.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Mok geel', 'FBEKER_GEEL', 'mok-geel', 'Geniet van je koffie of thee uit deze mok met de favoriete foto erop gedrukt. Dankzij de speciale druktechniek is de mok vaatwasmachinebestendig en kan deze in de magnetron.<br/>Deze mok is 9,5cm hoog en heeft een doorsnee van 8,2cm. Het handvat en de binnen kleur van deze mok zijn geel.', 16.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Mok roze', 'FBEKER_ROZE', 'mok-roze', 'Geniet van je koffie of thee uit deze mok met de favoriete foto erop gedrukt. Dankzij de speciale druktechniek is de mok vaatwasmachinebestendig en kan deze in de magnetron.<br/>Deze mok is 9,5cm hoog en heeft een doorsnee van 8,2cm. Het handvat en de binnen kleur van deze mok zijn roze.', 16.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Mok wit', 'FBEKER_WITE', 'mok-wit', 'Geniet van je koffie of thee uit deze mok met de favoriete foto erop gedrukt. Dankzij de speciale druktechniek is de mok vaatwasmachinebestendig en kan deze in de magnetron.<br/>Deze mok is 9,5cm hoog en heeft een doorsnee van 8,2cm. Het handvat en de binnen kleur van deze mok zijn wit.', 16.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Bierpul', 'FBIERPUL', 'bierpul', 'Geniet van je drankje uit deze stoere mok met de favoriete foto erop gedrukt. Dankzij de speciale druktechniek is de mok vaatwasmachinebestendig en kan deze in de magnetron. Deze mok is 13,5cm hoog. De binnen kleur van de mok is ook wit.', 19.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Dienblad', 'FDIENBLAD', 'dienblad', 'Dit mooie, grote dienblad van hout is 22cm x 35cm. Deze heeft een erg mooie afwerking en makkelijk schoon te houden door het kunststof bedrukte blad. Leuk voor bijvoorbeeld ontbijtjes op bed met vader- of moederdag.', 39.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Etui', 'FETUI', 'etui', 'Rondslingerende potloden en pennen is geen probleem meer! Met deze originele etui, met persoonlijke foto erop gedrukt, was het nog nooit zo makkelijk om alles bij elkaar te verzamelen. De etui is 23cm lang en 10cm breed.', 19.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Juwelendoos', 'FJUWELEN', 'juwelendoos', 'Je mooiste sieraden in de mooiste sieradendoos. Deze hardhouten doos is van stevige kwaliteit en beschermd al je mooie sieraden. De binnenkant hierin tegen is van zacht materiaal. Leuk als Moederdag cadeau (ook voor oma’s!). De doos is 20,5cm breed, 15,5 lang en 7cm hoog.', 39.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Kussensloop', 'FKUSSEN', 'kussensloop', 'Met je favoriete foto op je kussen kan je heerlijk wegdromen! Het goed gevulde witte kussen is 40cm x 40cm met een foto erop gedrukt van 20cm x 20cm', 24.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Brooddoos', 'FLUNCHBOX', 'brooddoos', 'Naamstickers zijn overbodig geworden; je bammetjes mee naar school in een trommel met je eigen foto erop! Hoe gaaf is dat? En dat er geen broodtrommels meer perongeluk verwisseld worden, is een ding wat zeker is. <br/>De broodtrommel is verkrijgbaar in de varianten (licht)blauw, roze en wit. Er zit een witte deksel, met foto, op en is 11.5 cm x 7.5 cm groot.', 19.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Muismat', 'FMUISMAT', 'muismat', 'Werk met meer plezier achter de pc. Dankzij deze muismat is dit geen probleem meer. De muismat wordt bedrukt met uw favoriete foto. Ook leuk als cadeau met bijvoorbeeld een foto van de hele familie erop gedrukt. De muismat is 19cm x 23 cm en heeft een schuimen achterkant.', 16.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Onderzetter', 'FONDERZETTER', 'onderzetter', 'Deze onderzetter is ontzettend leuk om thuis de glazen op te zetten. De onderzetter is voorzien van een harde bovenlaag, wat zorgt voor een mooie beschermlaag voor de foto . Aan de onderkant zit een kurklaag, waardoor de (glazen) tafel eventueel niet beschadigd. De onderzetter is 9,5cm x 9,5 cm.', 4.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Portemonnee (lederlook)', 'FPORTLEDER', 'portemonnee_leder', 'Deze luxe lederlook portemonnee is van alle gemakken voorzien. Er zitten genoeg vakjes in voor briefgeld, losgeld en zelfs voor de pasjes. Over de gehele, verharde voorzijde staat de gewenste foto gedrukt en maakt de portemonnee een uniek exemplaar. Deze portemonnee is 19cm lang en 10cm breed.', 25.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Portemonnee (blue jeans)', 'FPORTBLUE', 'portemonnee_blue', 'De donkerblauwe spijkerportemonnee is van alle gemakken voorzien. Er zitten genoeg vakjes in voor briefgeld, losgeld en zelfs voor de pasjes. Over de gehele, verharde voorzijde staat de gewenste foto gedrukt en maakt de portemonnee een uniek exemplaar. Deze portemonnee is 12cm lang en 8,5cm breed.', 24.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Puzzel (24 st.)', 'FPUZZEL', 'puzzel24', 'Op deze fotopuzzel van stevig materiaal wordt je favoriete foto afgedrukt. Zo kan je stukje voor stukje je herinneringen herbeleven. Het formaat van deze puzzel is 10cm x 15cm en de puzzel heeft 24 stukjes.', 15.00, 13.95, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Puzzel (120 st.)', 'FPUZ120', 'puzzel120', 'Op deze fotopuzzel van stevig materiaal wordt je favoriete foto afgedrukt. Zo kan je stukje voor stukje je herinneringen herbeleven. Het formaat van deze puzzel is 19cm x 28cm en de puzzel heeft 120 stukjes.', 18.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Puzzel (252 st.)', 'FPUZ252', 'puzzel252', 'Op deze fotopuzzel van stevig materiaal wordt je favoriete foto afgedrukt. Zo kan je stukje voor stukje je herinneringen herbeleven. Het formaat van deze puzzel is 28.5cm x 40cm en de puzzel heeft 252 stukjes.', 23.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Kookschort', 'FSCHORT', 'kookschort', 'Tijdens je optreden als kok of als chef-barbecue kun je de gasten nu niet alleen je kookkunst laten zien, maar ook je favoriete (familie)foto. Leuk voor bijvoorbeeld vader/moederdag.<br/> Het kookschort komt in 1 maat, maar kan met het lint op de juiste maat dicht gedaan worden. De afbeelding is mooi groot; 35cm breed en 28cm hoog.', 19.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Tas (klein)', 'FTAS', 'tas', 'Deze donkerblauwe spijkertas bestaat uit 1 groot vak, en wordt gesloten met rits en klittenband. De bedrukte voorkant kan er ook afgehaald worden, zodat de tas ook zonder afbeelding gebruikt kan worden. De tas is 22cm x 22cm en heeft een verstelbare riem.', 24.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Tas (groot)', 'FTASGROOT', 'tas-groot', 'Stoere schooltas met verstelbare draagriemen. De tas is gemaakt van zwarte denim canvasstof. De tas is 28cm x28cm en op de gehele voorflap wordt de gewenste foto gedrukt. De tas bestaat uit 1 groot vak en kan handig gesloten worden met een rits.', 37.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Slab blauw', 'FSLAB_BLAUW', 'slabblauw', 'Lekker knoeien en morsen met dit originele slabbetje bedrukt met je favoriete foto. Zo blijven de kleertjes lekker schoon en kan de slab gewoon in de wasmachine! Het slabbetje is in z’n geheel 36cm hoog en 30cm breed. De afbeelding zal 14cm hoog worden en 13cm breed.', 14.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Slab roze', 'FSLAB_ROZE', 'slabroze', 'Lekker knoeien en morsen met dit originele slabbetje bedrukt met je favoriete foto. Zo blijven de kleertjes lekker schoon en kan de slab gewoon in de wasmachine! Het slabbetje is in z’n geheel 36cm hoog en 30cm breed. De afbeelding zal 14cm hoog worden en 13cm breed.', 14.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Sleutelhanger', 'FSLEUTELHANGER', 'sleutelhanger', 'Wat is er nou leuker dan een fotootje aan je sleutelbos? Zo ziet iedereen meteen van wie deze sleutels zijn, en heb je altijd een foto bij de hand om mee te showen. Bij dit setje krijg je 6 pasfoto’s en een sleutelhanger, dus ook leuk om uit te delen!', 6.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Knuffelsleutelhanger hondje', 'FKNUFSLEUTELH', 'knuffel-sleutelhanger', 'Deze schattige viervoeter zorgt er misschien wel voor dat je sleutels nooit meer ergens rondslingeren. Deze kleine knuffelhond van 10cm hoog, moet je natuurlijk wel in de gaten houden. Hij draagt zelfs een shirt met je favoriete foto erop gedrukt, hoe origineel!', 13.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Spaarpot', 'FSPAARPOT', 'spaarpot', 'Sparen wordt nu nog leuker; met je leukste foto op de spaarpot wordt sparen een feest! De witte spaarpot van is van keramisch materiaal, is 9,5cm hoog en heeft een doorsnee van 8,2cm. Onderop zit een dop, waarmee de spaarpot eventueel geleegd kan worden (wat natuurlijk niet de bedoeling is!).', 16.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Tshirt S', 'FTSHIRT_S', 'tshirt-s', 'Leuk om voor een sportwedstrijd of een ander evenement een t-shirt aan te trekken met je favoriete (familie)foto erop! Dit witte t-shirt heeft een ronde hals en kan besteld worden in de maten S t/m XXL. De afbeelding is 23,5cm breed en 20cm hoog en staat aan de voorzijde.', 19.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Tshirt M', 'FTSHIRT_M', 'tshirt-m', 'Leuk om voor een sportwedstrijd of een ander evenement een t-shirt aan te trekken met je favoriete (familie)foto erop! Dit witte t-shirt heeft een ronde hals en kan besteld worden in de maten S t/m XXL. De afbeelding is 23,5cm breed en 20cm hoog en staat aan de voorzijde.', 19.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Tshirt L', 'FTSHIRT_L', 'tshirt-l', 'Leuk om voor een sportwedstrijd of een ander evenement een t-shirt aan te trekken met je favoriete (familie)foto erop! Dit witte t-shirt heeft een ronde hals en kan besteld worden in de maten S t/m XXL. De afbeelding is 23,5cm breed en 20cm hoog en staat aan de voorzijde.', 19.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Tshirt XL', 'FTSHIRT_XL', 'tshirt-xl', 'Leuk om voor een sportwedstrijd of een ander evenement een t-shirt aan te trekken met je favoriete (familie)foto erop! Dit witte t-shirt heeft een ronde hals en kan besteld worden in de maten S t/m XXL. De afbeelding is 23,5cm breed en 20cm hoog en staat aan de voorzijde.', 19.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Tshirt XXL', 'FTSHIRT_XXL', 'tshirt-xxl', 'Leuk om voor een sportwedstrijd of een ander evenement een t-shirt aan te trekken met je favoriete (familie)foto erop! Dit witte t-shirt heeft een ronde hals en kan besteld worden in de maten S t/m XXL. De afbeelding is 23,5cm breed en 20cm hoog en staat aan de voorzijde.', 19.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Drinkfles (bidon)', 'FBIDON', 'bidon', 'Maak je eigen unieke thermo drinkfles met foto. Goed voor 600 ml vloeistof en met twee soorten doppen. De drinkfles is bijvoorbeeld geschikt voor naar school of tijdens het sporten. Door de metalen behuizing blijft drank langer koel of warm. De drinkfles is voorzien van een haak waarmee de fles aan broek of tas gehangen kan worden.', 16.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Foto op sleutelhanger (rond)', 'FSLEUTEL_FOTO_RND', 'foto-sleutelhanger-vk', 'Hoe leuk is het als je je favoriete foto altijd bij je kunt dragen aan je sleutelbos? Leuk om te laten zien aan anderen, maar ook heel leuk om cadeau te doen. De sleutelhanger is van stevig materiaal, waardoor deze dus ook bestand is tegen alle weersomstandigheden! Tevens wordt de sleutelhanger aan beiden kanten bedrukt en is deze 6cm x 6cm.', 13.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Foto op sleutelhanger (hartje)', 'FSLEUTEL_FOTO_HRT', 'foto-sleutelhanger-hrt', 'Hoe leuk is het als je je favoriete foto altijd bij je kunt dragen aan je sleutelbos? Leuk om te laten zien aan anderen, maar ook heel leuk om cadeau te doen. De sleutelhanger is van stevig materiaal, waardoor deze dus ook bestand is tegen alle weersomstandigheden! Tevens wordt de sleutelhanger aan beiden kanten bedrukt en is deze 6cm x 6cm.', 13.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Tegel', 'FTEGEL', 'tegel', 'Deze keramieke tegel is ontzettend leuk om thuis op te hangen. Waterbestendig, dus ook leuk voor in de douche! De tegel is 15cm x 15xm en wordt bedrukt met de door u uitgekozen foto.', 14.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'iPad hoes', 'FIPAD_HOES', 'ipad-hoes', 'iPad hoes 23,5cm x 18cm bedrukt met je leukste foto. Een creatieve en zeer originele manier om je kostbare iPad te beschermen. Erg leuk om een familie foto hierop te laten drukken voor elk gezinslid dat de iPad gebruikt! Kan gebruikt worden voor de iPad 2, 3 en 4.', 34.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts'),
            (UUID(), 'Placemat', 'FPLACEMAT', 'placemat', 'Je kan nu eten van een placemat met je eigen foto erop. Of misschien wel een leuk cadeau met een foto van de hele familie erop? De placemat is 38cm breed en 25,5 cm hoog, dus groot genoeg voor ieder bord! ', 14.95, 21.00, NULL, 1, NOW(), NOW(), NULL, '', 'funproducts');
        ");
        
        $this->query("UPDATE `products` SET `high_shipping` = 1 WHERE `product_group` IN ('funproducts','canvas')");
    }
}
